# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R3jIP8av1DidQBvUdpaOGE_AhgYZrye2
"""

from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def index(request):
    return HttpResponse("조금만 기다려주세요. 10.27.(금) 발표 시 공개!")